# Generated by Django 4.0.6 on 2022-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('manufac_date', models.DateField()),
                ('description', models.TextField()),
                ('is_fresh', models.BooleanField(default=True)),
            ],
        ),
    ]
