# Generated by Django 4.0.6 on 2022-07-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruits',
            options={'ordering': ['-fruit_name']},
        ),
        migrations.AlterUniqueTogether(
            name='fruits',
            unique_together={('fruit_name', 'price')},
        ),
        migrations.AlterModelTable(
            name='fruits',
            table='Fruits Table',
        ),
    ]
