# Generated by Django 4.0.6 on 2022-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_fruits_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
